INSERT INTO [dbo].[SecurityQuestions] ([Id], [Question], [CreatedDate]) VALUES (1, N'What was your favorite place to visit as a child?', N'2018-07-24')
INSERT INTO [dbo].[SecurityQuestions] ([Id], [Question], [CreatedDate]) VALUES (2, N'Who is your favorite actor, musician, or artist?', N'2018-07-24')
INSERT INTO [dbo].[SecurityQuestions] ([Id], [Question], [CreatedDate]) VALUES (3, N'What is the name of your favorite pet?', N'2018-07-24')
INSERT INTO [dbo].[SecurityQuestions] ([Id], [Question], [CreatedDate]) VALUES (4, N'In what city were you born?', N'2018-07-24')
INSERT INTO [dbo].[SecurityQuestions] ([Id], [Question], [CreatedDate]) VALUES (5, N'What high school did you attend?', N'2018-07-24')
INSERT INTO [dbo].[SecurityQuestions] ([Id], [Question], [CreatedDate]) VALUES (6, N'What is the name of your first school?', N'2018-07-24')
INSERT INTO [dbo].[SecurityQuestions] ([Id], [Question], [CreatedDate]) VALUES (7, N'What is your favorite movie?', N'2018-07-24')
INSERT INTO [dbo].[SecurityQuestions] ([Id], [Question], [CreatedDate]) VALUES (8, N'What is your mother''s maiden name?', N'2018-07-24')
INSERT INTO [dbo].[SecurityQuestions] ([Id], [Question], [CreatedDate]) VALUES (9, N'What street did you grow up on?', N'2018-07-24')
INSERT INTO [dbo].[SecurityQuestions] ([Id], [Question], [CreatedDate]) VALUES (10, N'What was the make of your first car?', N'2018-07-24')
